Option Strict On
Imports System.EnterpriseServices
Imports System.Runtime.InteropServices
Imports Microsoft.Win32.RegistryKey

Imports Agi.Attr
Imports Agi.Plugin
Imports Agi.VectorGeometryTool.Plugin
Imports Agi.STKObjects
Imports Agi.STK.Plugin

' NOTE: Generate your own Guid using Microsoft's GuidGen.exe
' NOTE: Create your own ProgId to match your plugin's namespace and name
' NOTE: Specify the ClassInterfaceType.None enumeration, so the custom COM Interface 
' you created, i.e. IExample1, is used instead of an autogenerated COM Interface.
<JustInTimeActivation(True), _
GuidAttribute("830AA2C5-99CD-4e60-AA2E-EE0264438287"), _
ProgId("Agi.VGT.Axes.Plugin.Examples.VB_NET.Example1"), _
ClassInterface(ClassInterfaceType.None)> _
Public Class Example1
    Implements IExample1
    Implements IAgCrdnAxesPlugin
    Implements IAgUtPluginConfig

    Private m_AgAttrScope As Object
    Private m_CalcToolProvider As AgCrdnPluginCalcProvider
    Private m_DisplayName As String = "VB_NET.AxesExample"
    Private m_ICRFAxes As AgCrdnConfiguredAxes
    Private m_Site As AgStkPluginSite
    Private m_StkRootObject As AgStkObjectRoot
    Private m_TrueAnomaly As AgCrdnConfiguredCalcScalar
    Private m_VectorToolProvider As AgCrdnPluginProvider

    Private m_MyDouble As Double
    Private m_MyString As String

    Public Property MyDouble() As Double Implements IExample1.MyDouble

        Get
            Return m_MyDouble
        End Get
        Set(ByVal value As Double)
            m_MyDouble = value
        End Set

    End Property

    Public Property MyString() As String Implements IExample1.MyString

        Get
            Return m_MyString
        End Get
        Set(ByVal value As String)
            m_MyString = value
        End Set

    End Property

    Public Function Evaluate(ByVal Result As AgCrdnAxesPluginResultEval) As Boolean Implements IAgCrdnAxesPlugin.Evaluate

        If (m_ICRFAxes IsNot Nothing) Then
            Dim q1 As Double = 0
            Dim q2 As Double = 0
            Dim q3 As Double = 0
            Dim q4 As Double = 0

            m_ICRFAxes.CurrentValue(Result, q1, q2, q3, q4)
            Result.SetQuaternion(q1, q2, q3, q4)

            ' Rotate by 30 degrees. The parameters are expected to be in radians.
            Result.EulerRotate(AgECrdnEulerSequence.eCrdnEulerSequence121, 0.5236, 0.5236, 0.5236)
        End If

        Return True

    End Function

    Public Sub Free() Implements IAgCrdnAxesPlugin.Free

        Debug.WriteLine((Me.m_DisplayName & ".Free()"), "Entered:")

        Me.m_Site = Nothing
        Me.m_StkRootObject = Nothing
        Me.m_CalcToolProvider = Nothing
        Me.m_VectorToolProvider = Nothing
        Me.m_ICRFAxes = Nothing

        Debug.WriteLine((Me.m_DisplayName & ".Free()"), "Exited:")

    End Sub

    Public Function GetPluginConfig(ByVal pAttrBuilder As AgAttrBuilder) As Object Implements IAgUtPluginConfig.GetPluginConfig

        Debug.WriteLine((Me.m_DisplayName & ".GetPluginConfig()"), "Entered:")
        If (Me.m_AgAttrScope Is Nothing) Then
            Me.m_AgAttrScope = pAttrBuilder.NewScope
            pAttrBuilder.AddStringDispatchProperty(Me.m_AgAttrScope, "MyString", "A string", "MyString", &H10)
            pAttrBuilder.AddDoubleDispatchProperty(Me.m_AgAttrScope, "MyDouble", "A double", "MyDouble", 0)
        End If
        Debug.WriteLine((Me.m_DisplayName & ".GetPluginConfig()"), "Exited:")
        Return Me.m_AgAttrScope

    End Function

    Public Function Init(ByVal Site As IAgUtPluginSite) As Boolean Implements IAgCrdnAxesPlugin.Init

        Debug.WriteLine((Me.m_DisplayName & ".Init()"), "Entered:")
        Me.m_Site = DirectCast(Site, AgStkPluginSite)
        If (Me.m_Site IsNot Nothing) Then
            Me.m_StkRootObject = DirectCast(Me.m_Site.StkRootObject, AgStkObjectRoot)
        End If
        Debug.WriteLine((Me.m_DisplayName & ".Init()"), "Exited:")
        Return True

    End Function

    Public Sub Register(ByVal Result As AgCrdnAxesPluginResultReg) Implements IAgCrdnAxesPlugin.Register

        Debug.WriteLine((Me.m_DisplayName & ".Register()"), "Entered:")
        Dim objPath As String = ("[" & Result.ObjectPath & "]")
        Result.ShortDescription = ("Test short Desc: Component created using " & Me.m_DisplayName & " " & objPath)
        Result.LongDescription = ("Test long Desc: Component created using " & Me.m_DisplayName & " " & objPath)
        Dim oPath As String = Result.ObjectPath
        Dim parentPath As String = Result.ParentPath
        Dim grandParentPath As String = Result.GrandParentPath
        Debug.WriteLine(String.Concat(New String() {objPath, " Register() [objPath=", oPath, "] [parentPath=", parentPath, "] [grandParentPath=", grandParentPath, "]"}))
        Debug.WriteLine((Me.m_DisplayName & ".Register()"), "Exited:")

    End Sub

    Public Function Reset(ByVal Result As AgCrdnAxesPluginResultReset) As Boolean Implements IAgCrdnAxesPlugin.Reset

        Dim objPath As String = ("[" & Result.ObjectPath & "]")
        Debug.WriteLine((Me.m_DisplayName & ".Reset()"), "Entered:")

        Me.m_CalcToolProvider = Result.CalcToolProvider
        Me.m_VectorToolProvider = Result.VectorToolProvider
        Me.m_ICRFAxes = m_VectorToolProvider.ConfigureAxes("ICRF", "<MyObject>", "ICRF", "<MyObject>")

        Debug.WriteLine((Me.m_DisplayName & ".Reset()"), "Exited:")
        Return True

    End Function

    Public Sub VerifyPluginConfig(ByVal pPluginCfgResult As AgUtPluginConfigVerifyResult) Implements IAgUtPluginConfig.VerifyPluginConfig

        Debug.WriteLine((Me.m_DisplayName & ".VerifyPluginConfig()"), "Entered:")
        pPluginCfgResult.Result = True
        pPluginCfgResult.Message = "Ok"
        Debug.WriteLine((Me.m_DisplayName & ".VerifyPluginConfig()"), "Exited:")

    End Sub

End Class
