function [output] = feedbackTargeting(input)

switch input.method   
    
   case 'compute'
        computeData = input.methodData;        

        k = 2.0;        c = 0.8;
        scaleMtx    = computeData.IMtx;
        output.Torque = -scaleMtx*(k*computeData.erratt(1:3,1)*computeData.erratt(4,1)+c*computeData.att(5:7,1));        
      
    case 'register'
        
        output = {...
                 
                 {  'ArgumentName','att',...
                    'Type','Attitude',...
                    'Derivative','Yes',...
                    'ArgumentType','Input'},...

                 {  'ArgumentName','erratt',...
                    'Type','Attitude',...
                    'RefName','Body',...
                    'RefSource', 'Satellite/PerfectPointing',...
                    'ArgumentType','Input'},
                
                 {  'ArgumentName','IMtx',...
                    'Type','Inertia',...
                    'Name','Inertia',...
                    'ArgumentType','Input'};

        	     {  'ArgumentName','Torque',...
                    'Type','Parameter',...
                    'Name','Torque',...
                    'BasicType','Vector',...                    
                    'ArgumentType','Output'}...
       };
                                                     
    otherwise
       output = [];
end
