function output = gains(input)
%#inbounds
switch input.method   
    
   case 'compute'
        computeData = input.methodData;

        output.A = -0.1*eye(3);
        output.P = 200.0*eye(3);
        output.kq = 100.0;       %100 works a lot better than 10
        output.mode = -1;
        output.Gamma = 100.0*eye(6);
                
    case 'register'
        
        param0 = {  'ArgumentName','kq',...
                    'Type', 'Parameter',...
                    'BasicType','Double',...
                    'ArgumentType','Output'};

        param1 = {  'ArgumentName','P',...
                    'Type', 'Parameter',...
                    'BasicType','Matrix',...
                    'Size','3 3',...
                    'ArgumentType','Output'};

        param2 = {  'ArgumentName','A',...
                    'Type', 'Parameter',...
                    'BasicType','Matrix',...
                    'Size','3 3',...
                    'ArgumentType','Output'};
                                                  
        param3 = {  'ArgumentName','mode',...
                    'Type', 'Parameter',...
                    'BasicType','Double',...
                    'ArgumentType','Output'};
            
        param4 = {  'ArgumentName','Gamma',...
                    'Type', 'Parameter',...
                    'BasicType','Matrix',...
                    'Size','6 6',...
                    'ArgumentType','Output'};

        output = {param0, param1, param2, param3, param4};
    
    otherwise
       output = [];
end

