function output = track(input)
%#inbounds
switch input.method   
    
   case 'compute'
        computeData = input.methodData;

        A      = computeData.A;
        P      = computeData.P;

        q       = computeData.q;
        IMtx    = computeData.IMtx;
        wc      = computeData.wc;
        wcDot   = computeData.wcDot;
        z       = computeData.z;
        h       = computeData.h;
        mode    = computeData.mode;
        kq      = computeData.kq;
        
        
        q4 = q(4);
        qv = q(1:3,1);
        C=QuatToMtx(q);
        zDot = A*z+qv;
        nu = wc;
        nuCross = buildCross(nu);
        qvCross = buildCross(qv);
        Hp = IMtx*wcDot+nuCross*IMtx*nu;
        f = -0.5*kq*qv-0.5*q4*P*zDot+0.5*qvCross*P*zDot+Hp+nuCross*h;
        
        if mode > 0
            output.Torque = f;
            output.hDot = zeros(3,1);
        else
            output.Torque = zeros(3,1);
            output.hDot = -f;
        end            
        output.zDot = zDot;
                
    case 'register'
        
       param0 = {  'ArgumentName','mode',...
                    'Type','Parameter',...
                    'Name','mode',...
                    'Source','gains.m',...                    
                    'ArgumentType','Input'};

       param1 = {  'ArgumentName','q',...
                    'Type','Attitude',...
                    'RefName','Body',...
                    'RefSource','Satellite/Reference',...                    
                    'ArgumentType','Input'};

        param2 = {  'ArgumentName','IMtx',...
                    'Type','Inertia',...
                    'Name','Inertia',...
                    'ArgumentType','Input'};

        param3 = {  'ArgumentName','A',...
                    'Type','Parameter',...
                    'Name', 'A',...
                    'Source','gains.m',...                    
                    'ArgumentType','Input'};
            
        param4 = {  'ArgumentName','P',...
                    'Type','Parameter',...
                    'Name', 'P',...
                    'Source','gains.m',...                    
                    'ArgumentType','Input'};

       param5 = {   'ArgumentName','wc',...
                    'Type','Vector',...
                    'RefType','Attitude',...
                    'Name', 'AngVelocity',...
                    'Source','Satellite/Reference',...                    
                    'ArgumentType','Input'};

       param6 = {   'ArgumentName','wcDot',...
                    'Type','Vector',...
                    'RefType','Attitude',...
                    'Name', 'AngAccel',...
                    'Source','Satellite/Reference',...                    
                    'ArgumentType','Input'};
            
        param7 = {  'ArgumentName','h',...
                    'Type','Integral',...
                    'Name','MomentumBias',...
                    'ArgumentType','Input'};

        param8 = {  'ArgumentName','z',...
                    'Type','Integral',...
                    'Name','z',...
                    'ArgumentType','Input'};
            
        param9 = {  'ArgumentName','hDot',...
                    'Type','Parameter',...
                    'Name','hDot',...
                    'BasicType','Vector',...
                    'IntegralName','MomentumBias',...
                    'InitialCondition','0.0 0.0 0.0',...
                    'ArgumentType','Output'};

       param10 = {  'ArgumentName','zDot',...
                    'Type','Parameter',...
                    'Name','zDot',...
                    'BasicType','Vector',...
                    'IntegralName','z',...
                    'InitialCondition','0.0 0.0 0.0',...
                    'ArgumentType','Output'};
 
       param11 = {  'ArgumentName','Torque',...
                    'Type','Parameter',...
                    'BasicType','Vector',...
                    'Name','Torque',...
                    'ArgumentType','Output'};
 
      param12 = {  'ArgumentName','kq',...
                    'Type','Parameter',...
                    'Source','gains.m',...
                    'Name','kq',...
                    'ArgumentType','Input'};
             
      output = {param0, param1, param2, param3, param4, param5, param6, param7, param8, param9, param10, param11, param12};
    
    otherwise
       output = [];
end

