function [output] = Matlab_RadarSARNIIRSConstraint(input)
	% NOTE: the outputs that are returned
	%       MUST be in the same order as registered

	% NOTE: Please DO NOT change anything above or below the USER MODEL AREA.
	% 
	% This example shows static output parameters, but these parameters
      % may change value at each time step.

switch input.method
    
    case 'register'
 	% register output variables       
        RadarSARPluginConstraintValue = {'ArgumentName','RadarSARPluginConstraintValue',...
                     'Name','RadarSARPluginConstraintValue',...
                     'ArgumentType','Output'};
             
    % register input variables  
    
        DateUTC = {'ArgumentName','DateUTC',...
                'Name','DateUTC',...
                'ArgumentType','Input'};
        
        EpochSec = {'ArgumentName','EpochSec',...
                'Name','EpochSec',...
                'ArgumentType','Input'};
 
        CbName = {'ArgumentName','CbName',...
                  'Name','CbName',...
                  'ArgumentType','Input'};

        RadarPath = {'ArgumentName','RadarPath',...
               'Name','RadarPath',...
               'ArgumentType','Input'};
           
        TargetPath = {'ArgumentName','TargetPath',...
               'Name','TargetPath',...
               'ArgumentType','Input'};

        RadarTransmitPosCBF = {'ArgumentName','RadarTransmitPosCBF',...
               'Name','RadarTransmitPosCBF',...
               'ArgumentType','Input'};

        RadarTransmitAttitudeQuat = {'ArgumentName','RadarTransmitAttitudeQuat',...
               'Name','RadarTransmitAttitudeQuat',...
               'ArgumentType','Input'};
           
        RadarReceivePosCBF = {'ArgumentName','RadarReceivePosCBF',...
               'Name','RadarReceivePosCBF',...
               'ArgumentType','Input'};

        RadarReceiveAttitudeQuat = {'ArgumentName','RadarReceiveAttitudeQuat',...
               'Name','RadarReceiveAttitudeQuat',...
               'ArgumentType','Input'};
               
        TargetPosCBF= {'ArgumentName','TargetPosCBF',...
               'Name','TargetPosCBF',...
               'ArgumentType','Input'};
       
        TargetAttitudeQuat = {'ArgumentName','TargetAttitudeQuat',...
               'Name','TargetAttitudeQuat',...
               'ArgumentType','Input'};
    
        RadarTransmitterToTargetVecBF = {'ArgumentName','RadarTransmitterToTargetVecBF',...
               'Name','RadarTransmitterToTargetVecBF',...
               'ArgumentType','Input'};
           
        RadarReceiverToTargetVecBF = {'ArgumentName','RadarReceiverToTargetVecBF',...
                    'Name','RadarReceiverToTargetVecBF',...
                    'ArgumentType','Input'};
                
        TargetToRadarReceiverVecBF = {'ArgumentName','TargetToRadarReceiverVecBF',...
               'Name','TargetToRadarReceiverVecBF',...
               'ArgumentType','Input'};
           
        RadarTransmitterToTargetRange = {'ArgumentName','RadarTransmitterToTargetRange',...
               'Name','RadarTransmitterToTargetRange',...
               'ArgumentType','Input'};
           
        RadarReceiverToTargetRange = {'ArgumentName','RadarReceiverToTargetRange',...
                    'Name','RadarReceiverToTargetRange',...
                    'ArgumentType','Input'};
                
        AngleRate = {'ArgumentName','AngleRate',...
                    'Name','AngleRate',...
                    'ArgumentType','Input'};
            
        ConeAngle = {'ArgumentName','ConeAngle',...
                    'Name','ConeAngle',...
                    'ArgumentType','Input'};

       TransmitPropagationTime = {'ArgumentName','TransmitPropagationTime',...
                     'Name','TransmitPropagationTime',...
                     'ArgumentType','Input'};
             
        ReceivePropagationTime = {'ArgumentName','ReceivePropagationTime',...
                     'Name','ReceivePropagationTime',...
                     'ArgumentType','Input'};
                 
        TransmitRangeRate = {'ArgumentName','TransmitRangeRate',...
                     'Name','TransmitRangeRate',...
                     'ArgumentType','Input'};
             
        ReceiveRangeRate = {'ArgumentName','ReceiveRangeRate',...
                     'Name','ReceiveRangeRate',...
                     'ArgumentType','Input'};
    
        RadarSpeed = {'ArgumentName','RadarSpeed',...
                    'Name','RadarSpeed',...
                    'ArgumentType','Input'};

        RefractedElevationAngle = {'ArgumentName','RefractedElevationAngle',...
                     'Name','RefractedElevationAngle',...
                     'ArgumentType','Input'};
    
        RadarTransmitFrequency = {'ArgumentName','RadarTransmitFrequency',...
                    'Name','RadarTransmitFrequency',...
                    'ArgumentType','Input'};

       DopplerShiftedFrequencyAtTarget = {'ArgumentName','DopplerShiftedFrequencyAtTarget',...
                     'Name','DopplerShiftedFrequencyAtTarget',...
                     'ArgumentType','Input'};
    
        DopplerShiftedFrequencyAtRadarReceiver = {'ArgumentName','DopplerShiftedFrequencyAtRadarReceiver',...
                    'Name','DopplerShiftedFrequencyAtRadarReceiver',...
                    'ArgumentType','Input'};

        SARTimeAzimuthResolution = {'ArgumentName','SARTimeAzimuthResolution',...
                     'Name','SARTimeAzimuthResolution',...
                     'ArgumentType','Input'};
    
        SARMaxSceneWidth = {'ArgumentName','SARMaxSceneWidth',...
                    'Name','SARMaxSceneWidth',...
                    'ArgumentType','Input'};
    
        SARIntegrationTime = {'ArgumentName','SARIntegrationTime',...
                    'Name','SARIntegrationTime',...
                    'ArgumentType','Input'};

        SARAzimuthResolution = {'ArgumentName','SARAzimuthResolution',...
                     'Name','SARAzimuthResolution',...
                     'ArgumentType','Input'};
    
        SARRangeResolution = {'ArgumentName','SARRangeResolution',...
                    'Name','SARRangeResolution',...
                    'ArgumentType','Input'};

        SARAreaRate = {'ArgumentName','SARAreaRate',...
                    'Name','SARAreaRate',...
                    'ArgumentType','Input'};                

        SARSNR = {'ArgumentName','SARSNR',...
                    'Name','SARSNR',...
                    'ArgumentType','Input'}; 
                
        SARSCR = {'ArgumentName','SARSCR',...
                    'Name','SARSCR',...
                    'ArgumentType','Input'};

        SARCNR = {'ArgumentName','SARCNR',...
                    'Name','SARCNR',...
                    'ArgumentType','Input'};                

        SARPTCR = {'ArgumentName','SARPTCR',...
                    'Name','SARPTCR',...
                    'ArgumentType','Input'};  
                
        SAREffectiveNoiseBackScatter = {'ArgumentName','SAREffectiveNoiseBackScatter',...
                    'Name','SAREffectiveNoiseBackScatter',...
                    'ArgumentType','Input'}; 
                
        SARNoiseBandwidth = {'ArgumentName','SARNoiseBandwidth',...
                    'Name','SARNoiseBandwidth',...
                    'ArgumentType','Input'}; 
                
        SARNoisePower = {'ArgumentName','SARNoisePower',...
                    'Name','SARNoisePower',...
                    'ArgumentType','Input'};            
               
        SARSNRUnderJamming = {'ArgumentName','SARSNRUnderJamming',...
                    'Name','SARSNRUnderJamming',...
                    'ArgumentType','Input'}; 
                
        SARSCRUnderJamming = {'ArgumentName','SARSCRUnderJamming',...
                    'Name','SARSCRUnderJamming',...
                    'ArgumentType','Input'};       
                
        SARCNRUnderJamming = {'ArgumentName','SARCNRUnderJamming',...
                    'Name','SARCNRUnderJamming',...
                    'ArgumentType','Input'}; 
                
        SARJOverS = {'ArgumentName','SARJOverS',...
                    'Name','SARJOverS',...
                    'ArgumentType','Input'};  
                
        SARJammingPower = {'ArgumentName','SARJammingPower',...
                    'Name','SARJammingPower',...
                    'ArgumentType','Input'}; 
                
        output = {RadarSARPluginConstraintValue,...
                  DateUTC, EpochSec, CbName, RadarPath, TargetPath, RadarTransmitPosCBF, RadarTransmitAttitudeQuat,...
                  RadarReceivePosCBF, RadarReceiveAttitudeQuat, TargetPosCBF, TargetAttitudeQuat,...
                  RadarTransmitterToTargetVecBF, RadarReceiverToTargetVecBF, TargetToRadarReceiverVecBF,...
                  RadarTransmitterToTargetRange, RadarReceiverToTargetRange, AngleRate, ConeAngle,...
                  TransmitPropagationTime, ReceivePropagationTime, TransmitRangeRate, ReceiveRangeRate,...
                  RadarSpeed, RefractedElevationAngle, RadarTransmitFrequency, DopplerShiftedFrequencyAtTarget,...
                  DopplerShiftedFrequencyAtRadarReceiver, SARTimeAzimuthResolution, SARMaxSceneWidth, SARIntegrationTime,...
                  SARAzimuthResolution, SARRangeResolution, SARAreaRate, SARSNR, SARSCR, SARCNR, SARPTCR,...
                  SAREffectiveNoiseBackScatter, SARNoiseBandwidth, SARNoisePower,...
                  SARSNRUnderJamming, SARSCRUnderJamming, SARCNRUnderJamming, SARJOverS, SARJammingPower};
    
    case 'compute'
    
        computeData = input.methodData;

	% compute the Test Model : 
	% Example Model for testing only
	% RadarSAARNIIRSConstraint input & output parameter usage is shown
	% 

	% USER RadarSAARNIIRSConstraint MODEL AREA.
        
      time = computeData.EpochSec;
      
	  rdrxmtrPos = computeData.RadarTransmitPosCBF;
	  tgtPos = computeData.TargetPosCBF;
	  FreqAtTarget = computeData.DopplerShiftedFrequencyAtTarget;
	  RdrFreq = computeData.RadarTransmitFrequency;
       
	  range = norm(rdrxmtrPos  - tgtPos)/1000;
	  
	  DopplerShift = FreqAtTarget - RdrFreq; 
	  
	  rdrXmTgtZ = computeData.RadarTransmitterToTargetVecBF(3);
	  rdrXmTgtRange = computeData.RadarTransmitterToTargetRange;
	  SNR = computeData.SARSNR;
	  	
	  	m2In = 39.37007874015876;
	  	mic2m = 1.0e-6;
	  % 	lamda = 299792458.0 / FreqAtTarget;
	  	lamda = 0.65;
	  	D = 10;
	  	Q = 2;
	  	sinAngle = rdrXmTgtZ / rdrXmTgtRange;
	  	GSD = rdrXmTgtRange * lamda * mic2m / (Q * D * sqrt(sinAngle));
	  	a = 3.32;
	  	b = 1.559;
	  	RER = 0.9;
	  	Hgm = 1.0;
	  	G = 1.0;
	  	dlog10 = log(10.0);
	  	
	  	SARSNRLin = 10^(SNR/10.0);
	  	
	NIIRS = 10.251 - a * log(GSD * m2In)/dlog10 + b * log(RER)/dlog10 - 0.656 * Hgm - (0.344 * G / SARSNRLin);

      output.RadarSARPluginConstraintValue = NIIRS;
        
	% END OF USER MODEL AREA

    otherwise
        output = [];
end

