function [output] = Matlab_RadarSrchTrkConstraint(input)
	% NOTE: the outputs that are returned
	%       MUST be in the same order as registered

	% NOTE: Please DO NOT change anything above or below the USER MODEL AREA.
	% 
	% This example shows static output parameters, but these parameters
      % may change value at each time step.

switch input.method
    
    case 'register'
 	% register output variables       
        RadarSearchTrackPluginConstraintValue = {'ArgumentName','RadarSearchTrackPluginConstraintValue',...
                     'Name','RadarSearchTrackPluginConstraintValue',...
                     'ArgumentType','Output'};
             
    % register input variables  
    
        DateUTC = {'ArgumentName','DateUTC',...
                'Name','DateUTC',...
                'ArgumentType','Input'};
        
        EpochSec = {'ArgumentName','EpochSec',...
                'Name','EpochSec',...
                'ArgumentType','Input'};
 
        CbName = {'ArgumentName','CbName',...
                  'Name','CbName',...
                  'ArgumentType','Input'};

        RadarPath = {'ArgumentName','RadarPath',...
               'Name','RadarPath',...
               'ArgumentType','Input'};
           
        TargetPath = {'ArgumentName','TargetPath',...
               'Name','TargetPath',...
               'ArgumentType','Input'};

        RadarTransmitPosCBF = {'ArgumentName','RadarTransmitPosCBF',...
               'Name','RadarTransmitPosCBF',...
               'ArgumentType','Input'};

        RadarTransmitAttitudeQuat = {'ArgumentName','RadarTransmitAttitudeQuat',...
               'Name','RadarTransmitAttitudeQuat',...
               'ArgumentType','Input'};
           
        RadarReceivePosCBF = {'ArgumentName','RadarReceivePosCBF',...
               'Name','RadarReceivePosCBF',...
               'ArgumentType','Input'};

        RadarReceiveAttitudeQuat = {'ArgumentName','RadarReceiveAttitudeQuat',...
               'Name','RadarReceiveAttitudeQuat',...
               'ArgumentType','Input'};
               
        TargetPosCBF= {'ArgumentName','TargetPosCBF',...
               'Name','TargetPosCBF',...
               'ArgumentType','Input'};
       
        TargetAttitudeQuat = {'ArgumentName','TargetAttitudeQuat',...
               'Name','TargetAttitudeQuat',...
               'ArgumentType','Input'};
    
        RadarTransmitterToTargetVecBF = {'ArgumentName','RadarTransmitterToTargetVecBF',...
               'Name','RadarTransmitterToTargetVecBF',...
               'ArgumentType','Input'};
           
        RadarReceiverToTargetVecBF = {'ArgumentName','RadarReceiverToTargetVecBF',...
                    'Name','RadarReceiverToTargetVecBF',...
                    'ArgumentType','Input'};
                
        TargetToRadarReceiverVecBF = {'ArgumentName','TargetToRadarReceiverVecBF',...
               'Name','TargetToRadarReceiverVecBF',...
               'ArgumentType','Input'};
           
        RadarTransmitterToTargetRange = {'ArgumentName','RadarTransmitterToTargetRange',...
               'Name','RadarTransmitterToTargetRange',...
               'ArgumentType','Input'};
           
        RadarReceiverToTargetRange = {'ArgumentName','RadarReceiverToTargetRange',...
                    'Name','RadarReceiverToTargetRange',...
                    'ArgumentType','Input'};
                
        AngleRate = {'ArgumentName','AngleRate',...
                    'Name','AngleRate',...
                    'ArgumentType','Input'};
            
        ConeAngle = {'ArgumentName','ConeAngle',...
                    'Name','ConeAngle',...
                    'ArgumentType','Input'};

       TransmitPropagationTime = {'ArgumentName','TransmitPropagationTime',...
                     'Name','TransmitPropagationTime',...
                     'ArgumentType','Input'};
             
        ReceivePropagationTime = {'ArgumentName','ReceivePropagationTime',...
                     'Name','ReceivePropagationTime',...
                     'ArgumentType','Input'};
                 
        TransmitRangeRate = {'ArgumentName','TransmitRangeRate',...
                     'Name','TransmitRangeRate',...
                     'ArgumentType','Input'};
             
        ReceiveRangeRate = {'ArgumentName','ReceiveRangeRate',...
                     'Name','ReceiveRangeRate',...
                     'ArgumentType','Input'};
    
        RadarSpeed = {'ArgumentName','RadarSpeed',...
                    'Name','RadarSpeed',...
                    'ArgumentType','Input'};

        RefractedElevationAngle = {'ArgumentName','RefractedElevationAngle',...
                     'Name','RefractedElevationAngle',...
                     'ArgumentType','Input'};
    
        RadarTransmitFrequency = {'ArgumentName','RadarTransmitFrequency',...
                    'Name','RadarTransmitFrequency',...
                    'ArgumentType','Input'};

       DopplerShiftedFrequencyAtTarget = {'ArgumentName','DopplerShiftedFrequencyAtTarget',...
                     'Name','DopplerShiftedFrequencyAtTarget',...
                     'ArgumentType','Input'};
    
        DopplerShiftedFrequencyAtRadarReceiver = {'ArgumentName','DopplerShiftedFrequencyAtRadarReceiver',...
                    'Name','DopplerShiftedFrequencyAtRadarReceiver',...
                    'ArgumentType','Input'};

        ST_SinglePulseSNR = {'ArgumentName','ST_SinglePulseSNR',...
                     'Name','ST_SinglePulseSNR',...
                     'ArgumentType','Input'};
    
        ST_IntegratedSNR = {'ArgumentName','ST_IntegratedSNR',...
                    'Name','ST_IntegratedSNR',...
                    'ArgumentType','Input'};

        ST_NumIntegratedPulses = {'ArgumentName','ST_NumIntegratedPulses',...
                     'Name','ST_NumIntegratedPulses',...
                     'ArgumentType','Input'};
    
        ST_IntegrationTime = {'ArgumentName','ST_IntegrationTime',...
                    'Name','ST_IntegrationTime',...
                    'ArgumentType','Input'};

        ST_DwellTime = {'ArgumentName','ST_DwellTime',...
                     'Name','ST_DwellTime',...
                     'ArgumentType','Input'};
    
        ST_TargetRange = {'ArgumentName','ST_TargetRange',...
                    'Name','ST_TargetRange',...
                    'ArgumentType','Input'};

        ST_TargetVelocity = {'ArgumentName','ST_TargetVelocity',...
                    'Name','ST_TargetVelocity',...
                    'ArgumentType','Input'};                

        ST_TargetMLCVelocity = {'ArgumentName','ST_TargetMLCVelocity',...
                    'Name','ST_TargetMLCVelocity',...
                    'ArgumentType','Input'}; 
                
        ST_TargetInClearDopplerZone = {'ArgumentName','ST_TargetInClearDopplerZone',...
                    'Name','ST_TargetInClearDopplerZone',...
                    'ArgumentType','Input'};

        ST_TargetInMLCFilter = {'ArgumentName','ST_TargetInMLCFilter',...
                    'Name','ST_TargetInMLCFilter',...
                    'ArgumentType','Input'};                

        ST_TargetInSLCFilter = {'ArgumentName','ST_TargetInSLCFilter',...
                    'Name','ST_TargetInSLCFilter',...
                    'ArgumentType','Input'};  
                
        ST_UnambigRangeFlag = {'ArgumentName','ST_UnambigRangeFlag',...
                    'Name','ST_UnambigRangeFlag',...
                    'ArgumentType','Input'}; 
                
        ST_UnambigVelFlag = {'ArgumentName','ST_UnambigVelFlag',...
                    'Name','ST_UnambigVelFlag',...
                    'ArgumentType','Input'}; 
                
        ST_NoiseBandwidth = {'ArgumentName','ST_NoiseBandwidth',...
                    'Name','ST_NoiseBandwidth',...
                    'ArgumentType','Input'}; 
                
        ST_NoisePower = {'ArgumentName','ST_NoisePower',...
                    'Name','ST_NoisePower',...
                    'ArgumentType','Input'}; 
                
        ST_SinglePulseProbDetection = {'ArgumentName','ST_SinglePulseProbDetection',...
                    'Name','ST_SinglePulseProbDetection',...
                    'ArgumentType','Input'}; 
                
        ST_IntegratedProbDetection = {'ArgumentName','ST_IntegratedProbDetection',...
                    'Name','ST_IntegratedProbDetection',...
                    'ArgumentType','Input'}; 
                
        ST_NonCFARDetectThreshold = {'ArgumentName','ST_NonCFARDetectThreshold',...
                    'Name','ST_NonCFARDetectThreshold',...
                    'ArgumentType','Input'}; 
                
        ST_CFARThresholdMultiplier = {'ArgumentName','ST_CFARThresholdMultiplier',...
                    'Name','ST_CFARThresholdMultiplier',...
                    'ArgumentType','Input'};            
               
        ST_SinglePulseSNRUnderJamming = {'ArgumentName','ST_SinglePulseSNRUnderJamming',...
                    'Name','ST_SinglePulseSNRUnderJamming',...
                    'ArgumentType','Input'}; 
                
        ST_IntegratedSNRUnderJamming = {'ArgumentName','ST_IntegratedSNRUnderJamming',...
                    'Name','ST_IntegratedSNRUnderJamming',...
                    'ArgumentType','Input'}; 
                
        ST_SinglePulseProbDetectionUnderJamming = {'ArgumentName','ST_SinglePulseProbDetectionUnderJamming',...
                    'Name','ST_SinglePulseProbDetectionUnderJamming',...
                    'ArgumentType','Input'}; 
                
        ST_IntegratedProbDetectionUnderJamming = {'ArgumentName','ST_IntegratedProbDetectionUnderJamming',...
                    'Name','ST_IntegratedProbDetectionUnderJamming',...
                    'ArgumentType','Input'}; 
                
        ST_IntegrationTimeUnderJamming = {'ArgumentName','ST_IntegrationTimeUnderJamming',...
                    'Name','ST_IntegrationTimeUnderJamming',...
                    'ArgumentType','Input'}; 
                
        ST_NumIntegratedPulsesUnderJamming = {'ArgumentName','ST_NumIntegratedPulsesUnderJamming',...
                    'Name','ST_NumIntegratedPulsesUnderJamming',...
                    'ArgumentType','Input'};       
                
        ST_DwellTimeUnderJamming = {'ArgumentName','ST_DwellTimeUnderJamming',...
                    'Name','ST_DwellTimeUnderJamming',...
                    'ArgumentType','Input'}; 
                
        ST_JOverS = {'ArgumentName','ST_JOverS',...
                    'Name','ST_JOverS',...
                    'ArgumentType','Input'}; 
                
        ST_IntegratedJOverS = {'ArgumentName','ST_IntegratedJOverS',...
                    'Name','ST_IntegratedJOverS',...
                    'ArgumentType','Input'}; 
                
        ST_JammingPower = {'ArgumentName','ST_JammingPower',...
                    'Name','ST_JammingPower',...
                    'ArgumentType','Input'}; 
                
        output = {RadarSearchTrackPluginConstraintValue,...
                  DateUTC, EpochSec, CbName, RadarPath, TargetPath, RadarTransmitPosCBF, RadarTransmitAttitudeQuat,...
                  RadarReceivePosCBF, RadarReceiveAttitudeQuat, TargetPosCBF, TargetAttitudeQuat,...
                  RadarTransmitterToTargetVecBF, RadarReceiverToTargetVecBF, TargetToRadarReceiverVecBF,...
                  RadarTransmitterToTargetRange, RadarReceiverToTargetRange, AngleRate, ConeAngle,...
                  TransmitPropagationTime, ReceivePropagationTime, TransmitRangeRate, ReceiveRangeRate,...
                  RadarSpeed, RefractedElevationAngle, RadarTransmitFrequency, DopplerShiftedFrequencyAtTarget,...
                  DopplerShiftedFrequencyAtRadarReceiver, ST_SinglePulseSNR, ST_IntegratedSNR, ST_NumIntegratedPulses,...
                  ST_IntegrationTime, ST_DwellTime, ST_TargetRange, ST_TargetVelocity, ST_TargetMLCVelocity,...
                  ST_TargetInClearDopplerZone, ST_TargetInMLCFilter, ST_TargetInSLCFilter, ST_UnambigRangeFlag,...
                  ST_UnambigVelFlag, ST_NoiseBandwidth, ST_NoisePower, ST_SinglePulseProbDetection,...
                  ST_IntegratedProbDetection, ST_NonCFARDetectThreshold, ST_CFARThresholdMultiplier,...
                  ST_SinglePulseSNRUnderJamming, ST_IntegratedSNRUnderJamming, ST_SinglePulseProbDetectionUnderJamming,...
                  ST_IntegratedProbDetectionUnderJamming, ST_IntegrationTimeUnderJamming,...
                  ST_NumIntegratedPulsesUnderJamming, ST_DwellTimeUnderJamming, ST_JOverS, ST_IntegratedJOverS,...
                  ST_JammingPower};
    
    case 'compute'
    
        computeData = input.methodData;

	% compute the Test Model : 
	% Example Model for testing only
	% RadarSrchTrkConstraint input & output parameter usage is shown
	% 

	% USER RadarSrchTrkConstraint MODEL AREA.
        
      time = computeData.EpochSec;
      
	  rdrxmtrPos = computeData.RadarTransmitPosCBF;
	  tgtPos = computeData.TargetPosCBF;
	  IntegSNR = computeData.ST_IntegratedSNR;
       
	  range = norm(rdrxmtrPos  - tgtPos)/1000;

      output.RadarSearchTrackPluginConstraintValue = IntegSNR;
        
	% END OF USER MODEL AREA

    otherwise
        output = [];
end

