Option Strict On
Imports System.EnterpriseServices
Imports System.Runtime.InteropServices
Imports Microsoft.Win32.RegistryKey

Imports Agi.Attr
Imports Agi.Plugin
Imports Agi.VectorGeometryTool.Plugin
Imports Agi.STKObjects
Imports Agi.STK.Plugin

' NOTE: Generate your own Guid using Microsoft's GuidGen.exe
' NOTE: Create your own ProgId to match your plugin's namespace and name
' NOTE: Specify the ClassInterfaceType.None enumeration, so the custom COM Interface 
' you created, i.e. IExample1, is used instead of an autogenerated COM Interface.
<JustInTimeActivation(True), _
GuidAttribute("B5796BF4-8489-4b5e-B221-BE0CD2BFF93F"), _
ProgId("Agi.VGT.Vector.Plugin.Examples.VB_NET.Example1"), _
ClassInterface(ClassInterfaceType.None)> _
Public Class Example1
    Implements IExample1
    Implements IAgCrdnVectorPlugin
    Implements IAgUtPluginConfig

    Private m_AgAttrScope As Object
    Private m_CalcToolProvider As AgCrdnPluginCalcProvider
    Private m_DisplayName As String = "VB_NET.VectorExample"
    Private m_Site As AgStkPluginSite
    Private m_StkRootObject As AgStkObjectRoot
    Private m_VectorToolProvider As AgCrdnPluginProvider
    Private m_moonConfiguredVector As AgCrdnConfiguredVector
    Private m_sunConfiguredVector As AgCrdnConfiguredVector

    Private m_MyDouble As Double
    Private m_MyString As String

    Public Property MyDouble() As Double Implements IExample1.MyDouble

        Get
            Return m_MyDouble
        End Get
        Set(ByVal value As Double)
            m_MyDouble = value
        End Set

    End Property

    Public Property MyString() As String Implements IExample1.MyString

        Get
            Return m_MyString
        End Get
        Set(ByVal value As String)
            m_MyString = value
        End Set

    End Property

    ' Methods
    Public Function Evaluate(ByVal Result As AgCrdnVectorPluginResultEval) As Boolean Implements IAgCrdnVectorPlugin.Evaluate

        If ((Me.m_moonConfiguredVector IsNot Nothing) AndAlso (Me.m_moonConfiguredVector IsNot Nothing)) Then
            Dim x1 As Double = 0
            Dim y1 As Double = 0
            Dim z1 As Double = 0
            Me.m_moonConfiguredVector.CurrentValue(Result, x1, y1, z1)
            Dim x2 As Double = 0
            Dim y2 As Double = 0
            Dim z2 As Double = 0
            Me.m_sunConfiguredVector.CurrentValue(Result, x2, y2, z2)

            ' For this example, the vector is the average vector of the sun and the moon.
            Result.SetVectorComponents(((x2 + x1) / 2), ((y2 + y1) / 2), ((z2 + z1) / 2))
        End If

        Return True

    End Function

    Public Sub Free() Implements IAgCrdnVectorPlugin.Free

        Debug.WriteLine((Me.m_DisplayName & ".Free()"), "Entered:")

        Me.m_Site = Nothing
        Me.m_StkRootObject = Nothing
        Me.m_CalcToolProvider = Nothing
        Me.m_VectorToolProvider = Nothing
        Me.m_moonConfiguredVector = Nothing
        Me.m_sunConfiguredVector = Nothing

        Debug.WriteLine((Me.m_DisplayName & ".Free()"), "Exited:")

    End Sub

    Public Function GetPluginConfig(ByVal pAttrBuilder As AgAttrBuilder) As Object Implements IAgUtPluginConfig.GetPluginConfig

        Debug.WriteLine((Me.m_DisplayName & ".GetPluginConfig()"), "Entered:")
        If (Me.m_AgAttrScope Is Nothing) Then
            Me.m_AgAttrScope = pAttrBuilder.NewScope
            pAttrBuilder.AddStringDispatchProperty(Me.m_AgAttrScope, "MyString", "A string", "MyString", &H10)
            pAttrBuilder.AddDoubleDispatchProperty(Me.m_AgAttrScope, "MyDouble", "A double", "MyDouble", 0)
        End If
        Debug.WriteLine((Me.m_DisplayName & ".GetPluginConfig()"), "Exited:")
        Return Me.m_AgAttrScope

    End Function

    Public Function Init(ByVal Site As IAgUtPluginSite) As Boolean Implements IAgCrdnVectorPlugin.Init

        Debug.WriteLine((Me.m_DisplayName & ".Init()"), "Entered:")
        Me.m_Site = DirectCast(Site, AgStkPluginSite)
        If (Me.m_Site IsNot Nothing) Then
            Me.m_StkRootObject = DirectCast(Me.m_Site.StkRootObject, AgStkObjectRoot)
        End If
        Debug.WriteLine((Me.m_DisplayName & ".Init()"), "Exited:")
        Return True

    End Function

    Public Sub Register(ByVal Result As AgCrdnVectorPluginResultReg) Implements IAgCrdnVectorPlugin.Register

        Debug.WriteLine((Me.m_DisplayName & ".Register()"), "Entered:")
        Dim objPath As String = ("[" & Result.ObjectPath & "]")
        Result.ShortDescription = ("Test short Desc: Component created using " & Me.m_DisplayName & " " & objPath)
        Result.LongDescription = ("Test long Desc: Component created using " & Me.m_DisplayName & " " & objPath)
        Dim oPath As String = Result.ObjectPath
        Dim parentPath As String = Result.ParentPath
        Dim grandParentPath As String = Result.GrandParentPath
        Debug.WriteLine(String.Concat(New String() {objPath, " Register() [objPath=", oPath, "] [parentPath=", parentPath, "] [grandParentPath=", grandParentPath, "]"}))
        Debug.WriteLine((Me.m_DisplayName & ".Register()"), "Exited:")

    End Sub

    Public Function Reset(ByVal Result As AgCrdnVectorPluginResultReset) As Boolean Implements IAgCrdnVectorPlugin.Reset

        Dim objPath As String = ("[" & Result.ObjectPath & "]")
        Debug.WriteLine((Me.m_DisplayName & ".Reset()"), "Entered:")
        Me.m_CalcToolProvider = Result.CalcToolProvider
        Me.m_VectorToolProvider = Result.VectorToolProvider
        Me.m_moonConfiguredVector = Me.m_VectorToolProvider.ConfigureVector("Moon", "<MyObject>", "ICRF", "<MyObject>")
        Me.m_sunConfiguredVector = Me.m_VectorToolProvider.ConfigureVector("Sun", "<MyObject>", "ICRF", "<MyObject>")
        Debug.WriteLine((Me.m_DisplayName & ".Reset()"), "Exited:")
        Return True

    End Function

    Public Sub VerifyPluginConfig(ByVal pPluginCfgResult As AgUtPluginConfigVerifyResult) Implements IAgUtPluginConfig.VerifyPluginConfig

        Debug.WriteLine((Me.m_DisplayName & ".VerifyPluginConfig()"), "Entered:")
        pPluginCfgResult.Result = True
        pPluginCfgResult.Message = "Ok"
        Debug.WriteLine((Me.m_DisplayName & ".VerifyPluginConfig()"), "Exited:")

    End Sub

End Class
