version: '3.7'
services:
    stk-engine-connect:
        image: ansys/stk/stk-engine-connect:12.8.0-windowsservercore-ltsc2019
        build:
            context: .
            args:
                baseImage: ansys/stk/stk-engine-baseline:12.8.0-windowsservercore-ltsc2019
        ports:
            - 5001:5001
        env_file: ../configuration/licensing.env
